version: 2
jobs:
  test:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run: fastlane scan

workflows:
  version: 2
  test_release:
    jobs:
      - test
      - deploy:
          requires:
            test
          filters:
            branches:
              only: release
